language: cpp
compiler:
    - gcc
before_install:
    # disable rvm, use system Ruby
    - rvm reset
    - wget https://raw.githubusercontent.com/yast/yast-devtools/master/travis-tools/travis_setup.sh
    - sh ./travis_setup.sh -p "rake yast2-devtools yast2-testsuite yast2 yast2-storage yast2-xml yast2-transfer yast2-services-manager yast2-installation-control yast2-packager trang" -g "rspec:3.3.0 yast-rake gettext"
script:
    - rake check:syntax
    - rake check:pot
    - make -f Makefile.cvs
    - make
    - sudo make install
    - make check
    - ./check_schema.sh

